import { Geist, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Home/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700", "800", "900"],
});

export const metadata = {
  title: "Dhormopur Model Academy",
  description: "Generated by Dharmopur Model Academy Authority",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${roboto.variable} antialiased`}>
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
